#!/usr/bin/env bash
# Build the Next.js app natively and assemble the standalone output.
# Used by install.sh and update.sh — safe to re-run.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PKG_MGR="npm"
command -v bun >/dev/null 2>&1 && PKG_MGR="bun"

install_deps() {
  if [ "$PKG_MGR" = "bun" ]; then
    bun install --frozen-lockfile || bun install
    bunx prisma generate
  else
    npm install --no-audit --no-fund
    npx prisma generate
  fi
}

# Full clean-slate recovery: wipe node_modules AND all build state, then
# rebuild the dependency tree strictly from the lockfile (npm ci; falls back
# to npm install on very old npm clients).
install_deps_clean() {
  echo "==> Removing node_modules + .next for a clean rebuild…"
  rm -rf node_modules .next
  if [ "$PKG_MGR" = "bun" ]; then
    bun install --frozen-lockfile || bun install
    bunx prisma generate
  else
    npm ci --no-audit --no-fund || npm install --no-audit --no-fund
    npx prisma generate
  fi
}

build_app() {
  if [ "$PKG_MGR" = "bun" ]; then bun run build; else npm run build; fi
}

echo "==> Installing dependencies ($PKG_MGR)…"
install_deps

echo "==> Building app…"
# Stale build state (.next left over from a previous run, an interrupted build
# or a different Next.js version) can crash the new build with internal errors
# such as "TypeError: generate is not a function". Everything inside .next is
# fully regenerated by the build, so wiping it first is always safe.
rm -rf .next

if ! build_app; then
  # Self-heal: one shot at a completely clean rebuild before giving up. This
  # turns corrupted node_modules / poisoned caches (the classic "reinstall is
  # broken" on long-lived installs) into something the updater fixes by
  # itself in a single run, instead of telling the user to debug it.
  echo "⚠ build failed — retrying once with a completely clean tree…"
  install_deps_clean
  echo "==> Building app (clean tree)…"
  rm -rf .next
  if ! build_app; then
    echo "✗ build failed even after a clean reinstall — see the errors above" >&2
    exit 1
  fi
fi

echo "==> Assembling standalone output…"
# The package.json build script already copies static and public into standalone,
# but we clean and re-copy to ensure correctness after a previous failed build.
rm -rf .next/standalone/public .next/standalone/.next/static
cp -r public .next/standalone/public
mkdir -p .next/standalone/.next
cp -r .next/static .next/standalone/.next/static

# Preserve data directory inside standalone (update-state.json etc.)
mkdir -p .next/standalone/data
if [ -d "$ROOT/data" ]; then
  cp -a "$ROOT/data/." .next/standalone/data/ 2>/dev/null || true
fi

# Critical: copy package.json into standalone so runtime fallback
# src/lib/version.ts can read it even if NEXT_PUBLIC_APP_VERSION is missing.
# This also ensures `process.cwd()/package.json` returns correct version.
if [ -f "$ROOT/package.json" ]; then
  cp -a "$ROOT/package.json" .next/standalone/package.json
fi

# Verify build output
if [ ! -f .next/standalone/server.js ]; then
  echo "✗ build output is incomplete (standalone/server.js missing)" >&2
  exit 1
fi

# Verify that the built bundle contains the expected version
# (NEXT_PUBLIC_APP_VERSION is inlined at build time via next.config.ts)
BUILT_VERSION="$(grep -o '"version": *"[^"]*"' "$ROOT/package.json" | head -1 | cut -d'"' -f4)"
if [ -n "$BUILT_VERSION" ]; then
  STANDALONE_V="$(grep -o '"version": *"[^"]*"' .next/standalone/package.json 2>/dev/null | head -1 | cut -d'"' -f4)"
  if [ "$STANDALONE_V" != "$BUILT_VERSION" ]; then
    echo "⚠ standalone package.json version mismatch: $STANDALONE_V vs $BUILT_VERSION (will still work via inlined env)" >&2
  fi
fi

echo "✔ build complete (v${BUILT_VERSION:-unknown})"
